---
- name: 現在時刻を取得
  set_fact:
    now: "{{ lookup('pipe', 'TZ=JST-9 date +%Y%m%d%H%M%S') }}"

- name: 新規証明書のFingerprint取得
  command: "openssl x509 -in {{ bigip_src_crt_path }} -noout -sha256 -fingerprint"
  register: bigip_new_crt_fingerprint_result
  delegate_to: localhost
  changed_when: no

- name: 新規証明書のFingerprintを変数化
  set_fact:
    bigip_new_crt_fingerprint: "{{ bigip_new_crt_fingerprint_result.stdout | \
      regex_replace('^SHA256 Fingerprint=(.*)$', '\\1') }}"

- name: BIG-IPの証明書・秘密鍵情報を取得
  bigip_device_facts:
    provider: "{{ bigip_rest_provider }}"
    gather_subset:
      - client-ssl-profiles
      - ssl-certs
      - ssl-keys
  register: bigip_facts_result
  changed_when: no

- name: 現在のBIG-IPのClient SSL情報を変数化
  set_fact:
    bigip_current_crt_path: "{{ bigip_facts_result.client_ssl_profiles | \
      selectattr('name', '==', bigip_dest_ssl_profile_name) | \
      map(attribute='certificate_file') | first }}"

- name: 現在のBIG-IPの証明書情報を変数化
  set_fact:
    bigip_current_crt_name: "{{ bigip_facts_result.ssl_certs | \
      selectattr('full_path', '==', bigip_current_crt_path ) | \
      map(attribute='name') | first }}"
    bigip_current_crt_fingerprint: "{{ bigip_facts_result.ssl_certs | \
      selectattr('full_path', '==', bigip_current_crt_path ) | \
      map(attribute='fingerprint') | first | \
      regex_replace('^SHA256/(.*)$', '\\1') }}"

- block:
  - name: BIG-IPへ新規証明書をインポート
    bigip_ssl_certificate:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_dest_crt_name }}_{{ now }}"
      content: "{{ lookup('file', bigip_src_crt_path) }}"
    delegate_to: localhost

  - name: BIG-IPへ新規秘密鍵をインポート
    bigip_ssl_key:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_dest_crt_name }}_{{ now }}"
      content: "{{ lookup('file', bigip_src_key_path) }}"
    delegate_to: localhost

  - name: BIG-IPのClient SSL設定を変更
    bigip_profile_client_ssl:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_dest_ssl_profile_name }}"
      cert_key_chain:
        - cert: "{{ bigip_dest_crt_name }}_{{ now }}"
          key: "{{ bigip_dest_crt_name }}_{{ now }}"
    delegate_to: localhost

  - name: 現在のBIG-IPの証明書を削除
    bigip_ssl_certificate:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_current_crt_name }}"
      state: absent
    delegate_to: localhost

  - name: 現在のBIG-IPの秘密鍵を削除
    bigip_ssl_key:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_current_crt_name | regex_replace('^(.*)\\.crt$', '\\1.key') }}"
      state: absent
    delegate_to: localhost
  rescue:
  - name: BIG-IPのClient SSL設定を切り戻し
    bigip_profile_client_ssl:
      provider: "{{ bigip_rest_provider }}"
      name: "{{ bigip_dest_ssl_profile_name }}"
      cert_key_chain:
        - cert: "{{ bigip_current_crt_name }}"
          key: "{{ bigip_current_crt_name | regex_replace('^(.*)\\.crt$', '\\1.key') }}"
    delegate_to: localhost
  when: bigip_new_crt_fingerprint != bigip_current_crt_fingerprint